= Autoinstall Linux via USB
:keywords: linux, ubuntu
:revdate: 2024-10-27

These instructions are for automating the install of Ubuntu on to a physical machine without a monitor or keyboard.
Only two free USB slots and a network connection are required.

These instructions were created using Ubuntu Server 24.04 LTS.
They should also work for Ubuntu Desktop 24.04 LTS.

These instructions were heavily influenced by Jim Angel's https://www.jimangel.io/posts/automate-ubuntu-22-04-lts-bare-metal[How to automate a bare metal Ubuntu 22.04 LTS installation] and Subiquity's https://canonical-subiquity.readthedocs-hosted.com/en/latest/howto/autoinstall-quickstart.html[Autoinstall quick start].

== Host Prerequisites

* BIOS is configured to boot from USB stick before disk drive
* One free USB slot
* A network connection
* (optional) Monitor
* (optional) Keyboard

== Create Autoinstall Config

Files:

[listing]
----
meta-data
user-data
----

Create `meta-data`:

[listing]
----
touch meta-data
----

Create `user-data` with the following content:

[source,yaml]
.user-data
----
#cloud-config
autoinstall:
  version: 1
----

== Host the Configration

=== Option 1: Host on Webserver

WARNING: This method may or may not work due to a known https://github.com/canonical/cloud-init/issues/4044[race condition bug] in cloud-init.

. Serve the configuration using a webserver
+
[listing]
----
python -m http.server
----

. Insert the bootable USB stick
. Power on the machine
. At the GRUB menu,
.. Press 'e' to edit the GRUB configuration
. In the GRUB editor,
.. Modify the 'linux' line to be:
+
[listing]
----
linux ... autoinstall ds=nocloud\;s=http://CLOUD_CONFIG_HOST:8000
----
+
NOTE: Replace `CLOUD_CONFIG_HOST` with the address of the cloud config webserver.
+
NOTE: The semicolon after `ds=nocloud` must be escaped or GRUB will treat it as an end of statement.
.. Press 'Ctrl+x' to boot

=== Option 2: Host on USB Drive

Create a USB stick with the following properties:

* Volume filesystem: vfat or fat32
* Volume label: `CIDATA`

Cloud-init will automatically treat any volume with the label `CIDATA` as a datasource.

[appendix]
== Modify ISO for non-interactive autoinstall

[appendix]
== Configure Ventoy for autoinstall

Create a Ventoy bootable USB stick with 3 partitions below 137GB.

Paritions:

. (exFAT) Main partition to hold ISO files
. (FAT) Boot partition to hold Ventoy files
. (vFAT) Config partition to hold cloud config files
+
IMPORTANT: This partition must be labeled "CIDATA".

Steps:

. Run Ventoy2Disk
. Select the Option>Partition Configuration menu item
. Enable Preserve some space at the end of the disk
. Set preserved space to:
** If usb_stick_size > 137GB: (usb_stick_size - 137GB) + 128MB
** If usb_stick_size <= 137GB: 128MB

References:

* https://www.ventoy.net/en/doc_disk_layout.html[Ventoy Disk Layout In MBR]
* https://www.ventoy.net/en/doc_disk_layout_gpt.html[Ventory Disk Layout In GPT]
* https://www.ventoy.net/en/doc_legacy_limit.html[Legacy BIOS Access Range Limitation]
