= Autoinstall Linux via USB
:keywords: linux, ubuntu
:revdate: 2024-10-27

These instructions are for automating the install of Ubuntu on to a physical machine.

These instructions were created using Ubuntu Server 24.04 LTS but they are also applicable to Ubuntu Desktop.

These instructions were heavily influenced by Jim Angel's https://www.jimangel.io/posts/automate-ubuntu-22-04-lts-bare-metal[How to automate a bare metal Ubuntu 22.04 LTS installation] and Subiquity's https://canonical-subiquity.readthedocs-hosted.com/en/latest/howto/autoinstall-quickstart.html[Autoinstall quick start].
Jim's howto requires 2 USB sticks while this howto only requires one.
Jim's howto requires modification of the ISO for headless install while this howto does not.
Both of these enhancements are enabled via Ventoy.

== Host Prerequisites

* BIOS is configured to boot from USB stick before disk drive
* One free USB slot
* A network connection
* (optional) Monitor
* (optional) Keyboard

== Install Ventoy to USB Stick

. Download Ventoy from https://www.ventoy.net/en/download.html
. Run `Ventoy2Disk`
. Select Device
. Install with default options

== USB Stick Contents

[listing]
----
Ventoy volume
├── ventoy
|   ├── autoinstall
|   |   ├── cloud-init-user-data-1.yml
|   |   └── cloud-init-user-data-N.yml
|   └── ventoy.json <== Ventoy configuration
└── isos
    ├── ubuntu-server-24.04.iso
    └── ubuntu-desktop-24.04.iso
----

== Add ISOs to USB Stick

. Create `/isos` directory on the USB stick "Ventoy" volume.

. Add the Ubuntu Server and/or Ubuntu Desktop ISOs to this directory.

== Configure Ventoy Timeouts

[source,json]
.`/ventoy/ventoy.json`
----
{
    "control":[
        { "VTOY_MENU_TIMEOUT": "5" },
        { "VTOY_DEFAULT_IMAGE": "/isos/ubuntu-24.04.1-live-server-amd64.iso" },
        { "VTOY_SECONDARY_BOOT_MENU": "1" },
        { "VTOY_SECONDARY_TIMEOUT": "5" }
    ]
}
----

== Add Autoinstall Configs to USB Stick

. Create `/ventoy/autoinstall` directory on the USB stick "Ventoy" volume.
. Create one file per configuration in `/ventoy/autoinstall`

=== Add Autoinstall Configs to Ventoy Config

[source,json]
.`/ventoy/ventoy.json`
----
{
    "control":[
        { "VTOY_MENU_TIMEOUT": "5" },
        { "VTOY_DEFAULT_IMAGE": "/isos/ubuntu-24.04.1-live-server-amd64.iso" },
        { "VTOY_SECONDARY_BOOT_MENU": "1" },
        { "VTOY_SECONDARY_TIMEOUT": "5" }
    ]
    "auto_install":[
        {
            "image": "/isos/ubuntu-24.04.1-live-server-amd64.iso",
            "template":[
                "/ventoy/autoinstall/ubuntu-server-24.04.yml",
                "/ventoy/autoinstall/ubuntu-desktop-24.04.yml"
            ],
            "timeout": 10,
            "autosel": 1
        }
    ]
}
----

[appendix]
== Test using VirtualBox

. Create a new VM
** Name and Operating System
*** Name: `autoinstall-test`
*** Type: `Linux`
*** Subtype: `Ubuntu`
*** Version: `Ubuntu (64-bit)`
** Hardware
*** Base Memory: 8192 MB
*** CPUs: 2
*** Enable EFI

. Edit VM settings
** USB
... Select USB 3.0 (if stick supports it)
... Add new USB filter
... Select USB stick

. Start the VM

. Sit back and let the install happen
